#lang racket

(son Adam Cain)
(son Cain Enoch)
(son Enoch Irad)
(son Irad Mehujael)
(son Mehujael Methushael)
(son Methushael Lamech)
(wife Lamech Ada)
(son Ada Jabal)
(son Ada Jubal)

(rule (grandson ?x ?y)
      (and (son ?x ?z)
           (son ?z ?y)))

(rule (son ?x ?y)
      (and (wife ?z ?y)
           (son ?x ?z)))

'(son ?x ?y)
(son Ada Jubal)
(son Ada Jabal)
(son Methushael Lamech)
(son Mehujael Methushael)
(son Irad Mehujael)
(son Enoch Irad)
(son Cain Enoch)
(son Adam Cain)
(son Methushael Ada)

'(grandson Cain ?y)
(grandson Cain Irad)

'(grandson ?y Methushael)
(grandson Irad Methushael)

'(grandson ?x ?y)
(grandson Mehujael Lamech)
(grandson Irad Methushael)
(grandson Mehujael Ada)
(grandson Enoch Mehujael)
(grandson Cain Irad)
(grandson Adam Enoch)
(grandson Methushael Jubal)
(grandson Methushael Jabal)
